receivers:
  #jaeger:
  #  endpoint: 0.0.0.0:55678
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
  zipkin:
    endpoint: 0.0.0.0:9411

exporters:
  #jaeger:
  #  endpoint: jaeger-all-in-one:14250
  logging:
  #prometheus:
  #  endpoint: "0.0.0.0:8889"
  #  namespace: promexample
  #  const_labels:
  #    label1: value1
  #zipkin:
  #  url: "http://zipkin-all-in-one:9411/api/v2/spans"
  #  format: proto

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [logging]
      processors: [batch, queued_retry]
    metrics:
      receivers: [prometheus]
      exporters: [logging]
